on: [push]

jobs:
  hello_kotlin_docker_job:
    runs-on: ubuntu-latest
    name: A job to say Hello World!
    steps:
      - name: Hello world action step
        uses: ziem/hello-kotlin-docker-action@main
        with:
          who-to-greet: 'Kotlin'
